env:
   global:
     - CONAN_USERNAME: "francescalted"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/blosc/conan-blosc"
     - CONAN_REMOTES: "https://api.bintray.com/conan/blosc/conan-blosc"
     - CONAN_ARCHS: "x86,x86_64"
     
linux: &linux
   os: linux
   sudo: required
   dist: trusty
   language: python
   python: "3.6"
osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        compiler: gcc

      - <<: *osx
        compiler: clang
        osx_image: xcode8.3


before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

install:
  - bash scripts/install.sh
  
script:
   - bash scripts/run.sh

  
