env:
   global:
     - CONAN_REFERENCE: "c-blosc/0.2"
     - CONAN_USERNAME: "albertosm27"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_REMOTES: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_ARCHS: "x86,x86_64"
     
linux: &linux
   os: linux
   sudo: required
   dist: trusty
   language: python
   python: "3.6"
osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        compiler: gcc

      - <<: *linux
        compiler: clang

      - <<: *osx
        compiler: gcc
        osx_image: xcode8.3

      - <<: *osx
        compiler: clang
        osx_image: xcode8.3


before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

install:
  - bash scripts/install.sh
  - echo ${TRAVIS_BRANCH}

deploy:
  on:
    tags: true
    
after_deploy:
  - bash scripts/run.sh
