env:
   global:
     - CONAN_REFERENCE: "c-blosc/0.1"
     - CONAN_USERNAME: "albertosm27"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_REMOTES: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_ARCHS: "x86, x86_64"
     - CONAN_TOTAL_PAGES: 2
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_ARCHS=x86 CONAN_DOCKER_IMAGE=stable/gcc6.3x86 CONAN_CURRENT_PAGE=1

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=stable/gcc6.3x64 CONAN_CURRENT_PAGE=1

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_ARCHS=x86 CONAN_DOCKER_IMAGE=stable/clang4x86 CONAN_CURRENT_PAGE=2

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=stable/clang4x64 CONAN_CURRENT_PAGE=2

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_GCC_VERSIONS=6.3 CONAN_ARCHS=x86 CONAN_CURRENT_PAGE=1

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_GCC_VERSIONS=6.3 CONAN_ARCHS=x86_64 CONAN_CURRENT_PAGE=2

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_ARCHS=x86 CONAN_CURRENT_PAGE=1

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_ARCHS=x86_64 CONAN_CURRENT_PAGE=2


before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

install:
  - bash scripts/install.sh

script:
  - bash scripts/run.sh
  
