language: c
sudo: required
env:
   global:
     - CONAN_REFERENCE: "lib/1.0"
     - CONAN_USERNAME: "albertosm27"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_REMOTES: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_ARCHS: "x86, x86_64"
     
os:
- linux
- osx

compiler:
  - gcc
  - clang

before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build . --config Release
  - ctest
  - chmod +x scripts/conan.sh
  - ./scripts/conan.sh
  
