language: c

env:
   global:
     - CONAN_REFERENCE: "lib/1.0"
     - CONAN_USERNAME: "albertosm27"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_REMOTES: "https://api.bintray.com/conan/albertosm27/c-blosc-test"
     - CONAN_ARCHS: "x86, x86_64"
     
os:
- linux
- osx

compiler:
  - gcc
  - clang

before_install: ./scripts/travis-before-install.sh

#install: sudo apt-get install libsnappy-dev zlib1g-dev
#install: sudo apt-get install liblz4-dev libsnappy-dev zlib1g-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build . --config Release
  - ctest
  - chmod +x .travis/install.sh
  - if [[ "$(uname -s)" == 'Darwin' ]]; then
  -    brew update || brew update
  -    brew outdated pyenv || brew upgrade pyenv
  -    brew install pyenv-virtualenv
  -    brew install cmake || true
  -    if which pyenv > /dev/null; then
  -        eval "$(pyenv init -)"
  -    fi
  -    pyenv install 2.7.10
  -    pyenv virtualenv 2.7.10 conan
  -    pyenv rehash
  -    pyenv activate conan
  - fi
  - pip install conan --upgrade
  - pip install conan_package_tools
  - conan user
  - if [[ "$(uname -s)" == 'Darwin' ]]; then
  -    if which pyenv > /dev/null; then
  -        eval "$(pyenv init -)"
  -    fi
  - pyenv activate conan
  - fi
  - python build.py
  
